//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medicalsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chabter1_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chabter1_Tbl()
        {
            this.Section_Tbl = new HashSet<Section_Tbl>();
        }
    
        public int ID { get; set; }
        public string CodeRange_from { get; set; }
        public string CodeRange_To { get; set; }
        public string SectionDescription { get; set; }
        public string link_data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section_Tbl> Section_Tbl { get; set; }
    }
}
