//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medicalsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diseases_destails_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diseases_destails_tbl()
        {
            this.dises_Description_tbl = new HashSet<dises_Description_tbl>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Link_data { get; set; }
        public Nullable<int> Diseases_fk { get; set; }
    
        public virtual Diseases_Tbl Diseases_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dises_Description_tbl> dises_Description_tbl { get; set; }
    }
}
