//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medicalsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class dises_Description_tbl
    {
        public int ID { get; set; }
        public string Descraption { get; set; }
        public string code_dec { get; set; }
        public Nullable<int> details_fk { get; set; }
        public string img { get; set; }
        public string Specialty { get; set; }
        public string MeSH_Codes { get; set; }
        public string ICD9Codes { get; set; }
    
        public virtual Diseases_destails_tbl Diseases_destails_tbl { get; set; }
    }
}
