//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medicalsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section_Tbl()
        {
            this.Diseases_Tbl = new HashSet<Diseases_Tbl>();
        }
    
        public int ID { get; set; }
        public string Code_to { get; set; }
        public string Code_from { get; set; }
        public string Name { get; set; }
        public Nullable<int> Chabter1_fk { get; set; }
        public string link_data { get; set; }
    
        public virtual Chabter1_Tbl Chabter1_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diseases_Tbl> Diseases_Tbl { get; set; }
    }
}
